### ISSUE TITLE
Not parsing when contents contains "?".

### ISSUE THREAD

**Issue by dex-labs** [nicinabox/shortcode.js#4]
Am having issues when the contents of my shortcode element has a "?" (question mark) in it.
#### Works:

```
[fullwidth]
Are you Ready.
[/fullwidth]
```
#### Fails:

```
[fullwidth]
Are you Ready?
[/fullwidth]
```

My guess is the regular expression used in matchTags needs to be modified.

**Comment by nicinabox** [comment]
Thanks! Should now be fixed on master (7ea6a0a)

**Comment by dex-labs** [comment]
Sorry about the trouble would fix this myself but regex is my cryptonite.

Still doesn't parse when the ? is on a newline.

#### Works:

```
 [question]Hello?[/question]
```

#### Fails:

```
[question]
Hello?
[/question]
```
- Notes the line breaks.

**Comment by nicinabox** [comment]
Hmm, looks like the test fails with linebreaks, but for a different reason. The contents seem to be captured correctly. I'll look into it.

**Comment by nicinabox** [comment]
Actually, it seems to match twice. Once with `[question]` as a single tag, and again as a matched pair.

**Comment by nicinabox** [comment]
@dex-labs try again on master

**Comment by dex-labs** [comment]
weird error when html tag is inside content.

http://jsbin.com/niduca/1/edit?html,js,output

**Comment by nicinabox** [comment]
That one threw me for a loop. Give it a try on master.

**Comment by dex-labs** [comment]
Sweet. Seems to be functioning well so far.
